### PR TITLE
add TCP keep-alive to client side

### PR DESCRIPTION
**Pull request by sigxcpu76**

### CODE REVIEW

**Comment by sigxcpu76** [comment]
This patches the client-side TCP connection with keep-alive (60 seconds interval) as a fix for #147

**Comment by hfwang** [comment]
Sorry for the long delay. The change looks good!

I'm going to pull this into the Google internal repository, and test it internally for this week, assuming all goes well, I'll merge this!

**Comment by robsonpeixoto** [comment]
News @hfwang ?

**Comment by hfwang** [comment]
Some comments were made when this was reviewed internally, I've piled on some extra log lines and removed the call to SetLinger. Over to easwars for review!

**Pull request merged**
