### PR TITLE
chore(docs): Remove "v" from container image tags

### LINKED ISSUE #418: Wrong Docker Image Tags
## Description
The docs say the following Docker image tags are available:

> - v$VERSION - default image (recommended)
> - v$VERSION-alpine - uses alpine:3 as a base image
> - v$VERSION-buster - uses debain:buster as a base image

If you check us.gcr.io/cloudsql-docker/gce-proxy, you're actually tagging images like `$VERSION`, `v$VERSION-alpine`, and `v$VERSION-buster`. Also, `v$VERSION-alpine` and `v$VERSION-buster` only exist for `v1.17`.

## Solution
Update the docs to match the actual docker image tags that are and will be available.

### PR DESCRIPTION
**Pull request by shubha-rajan**
## Change Description

Updated documentation for proxy container images in README.md

## Relevant issues:

- Fixes #418

### CODE REVIEW

**Comment by kurtisvg** [comment]
So I'd actually prefer if we stuck to using `v$VERSION` so it's consistent with the release tag we have to use on GitHub. If we take this course of action, there are a few choices to make:

1. Do we backport `v$VERSION` tag to previous versions? (probably)
2. Do we continue to push both versions of the tag in the future? If so, we'll need to update the default Cloud Build configuration.

**Comment by kurtisvg** [comment]
> So I'd actually prefer if we stuck to using `v$VERSION` so it's consistent with the release tag we use on GitHub. If we go this route, there are a few choices to make:
> 
> 1. Do we backport `v$VERSION` tag to previous versions? (probably)
> 2. Do we continue to push both versions of the tag in the future? If so, we'll need to update the default Cloud Build configuration.

**Comment by shubha-rajan** [comment]
I think backporting makes sense. As for pushing both versions in the future, would it break users if we only pushed the `v$VERSION` and do we want to officially support both tags?

**Comment by kurtisvg** [comment]
Do you mind fixing the BUILD files in this PR as well?

**Pull request merged**
