### PR TITLE
add support for watching instances via file

### PR DESCRIPTION
**Pull request by night**
The company I work for uses confd for configuration management, and we wanted a way to reload the instances list without restarting the process. This seems to work well enough.

### CODE REVIEW

**Comment by night** [comment]
I signed it!

**Comment by kurtisvg** [comment]
@night Your CLA check is still failing - would you please double check the instructions listed in the post and make sure you didn't miss any steps?

**Comment by night** [comment]
@kurtisvg I see the CLA listed under `Corporate Agreements` at https://cla.developers.google.com/clas and the emails match up .. possible there is some kind of delay/bug? I posted right after it was signed.

**Comment by kurtisvg** [comment]
@night Thanks! The bot rechecks when you comment (you may have commented before the change had propagated to the bot the first time)

**Comment by hfwang** [comment]
@night I've been mulling this over for awhile, and I'm a bit hesitant to take this. While I understand why this feature is valuable to you, it feels like the number of ways that you can specify and configure the proxy client is constantly ballooning and that has made things harder to maintain.

I'm curious, for your use case, is it possible to use either fuse, or the instance metadata (which is used for GCE VMs) to solve your problem?

If not, would you mind opening an issue as a way to guage demand and see if other folks are interested in this functionality?

**Comment by kurtisvg** [comment]
We are going to close this for now, please feel free to open an issue to better gauge support if you feel strongly about this feature.

**Pull request closed without merging**
