### PR TITLE
Add some Prometheus metrics:

### LINKED ISSUE #169: Add support for metrics / tracing
Hi,
It would be great to be able to track metrics from the proxy (connections, disconnects, etc) in prometheus. If you're open to a PR on this, I can create one

### PR DESCRIPTION
**Pull request by tomwilkie**
## Change Description

Add some Prometheus metrics:
- cloudsql_proxy_active_connections
- cloudsql_proxy_max_connections
- cloudsql_proxy_connections_total
- cloudsql_proxy_connections_errors_total

## Checklist

- [x] Make sure to open an issue as a 
  [bug/issue](https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/new/choose) 
  before writing your code!  That way we can discuss the change, evaluate 
  designs, and agree on the general idea.
- [ ] Ensure the tests and linter pass
- [ ] Appropriate documentation is updated (if necessary)

## Relevant issues:

- Fixes #169

### CODE REVIEW

**Comment by kurtisvg** [comment]
2 quick high level thoughts: 

1. I'd much rather target Opencensus and be able to support Prometheus and Stackdriver metrics as well
2. We probably (at least initially) mark the flag as experimental - particularly because I would ideally like to be able to provide more instance specific connections, and don't want to have to do a major version bump if that effects the metric surface.

**Comment by Carrotman42** [comment]
Just so that we are clear about what the impact of adding this dependency is, do you mind reporting the before/after size of the binary?

**Comment by tomwilkie** [comment]
> I'd much rather target Opencensus and be able to support both Prometheus and Stackdriver metrics

I thought Opencensus was deprecated and Opentelemetry wasn't ready yet...  Either way not super familiar with either.  I think there are plenty of ways to get Prometheus metrics into stackdriver.

> We probably (at least initially) mark the flag as experimental - particularly because I would ideally like to be able to provide more instance specific connections, and don't want to have to do a major version bump if that effects the metric surface.

Done!

> Just so that we are clear about what the impact of adding this dependency is, do you mind reporting the before/after size of the binary?

```
twilkie@MacBook-Pro cloudsql-proxy % git checkout  master 
twilkie@MacBook-Pro cloudsql-proxy % GOOS=linux go build ./cmd/cloud_sql_proxy
twilkie@MacBook-Pro cloudsql-proxy % ls -l cloud_sql_proxy                   
-rwxr-xr-x  1 twilkie  staff  16391258 15 Oct 09:50 cloud_sql_proxy
```

```
twilkie@MacBook-Pro cloudsql-proxy % git checkout  prometheus 
Switched to branch 'prometheus'
twilkie@MacBook-Pro cloudsql-proxy % GOOS=linux go build ./cmd/cloud_sql_proxy
twilkie@MacBook-Pro cloudsql-proxy % ls -l cloud_sql_proxy                    
-rwxr-xr-x  1 twilkie  staff  17930396 15 Oct 09:51 cloud_sql_proxy
```

**Comment by kurtisvg** [comment]
> I thought Opencensus was deprecated and Opentelemetry wasn't ready yet... Either way not super familiar with either. I think there are plenty of ways to get Prometheus metrics into stackdriver.

OpenCensus isn't deprecated, but most of the feature work is focused on OpenTelemetry. OpenTelemetry is currently in Beta and is supposed to GA sometime before the end of the year. 

You can export Prometheus metrics to Stackdriver, but requires you to collect them in a prometheus server and export them. Using OpenCensus means we could provide users an option to specify an exporter to either Prometheus or Stackdriver (or one of the other supported exporters).

**Comment by withnale** [comment]
Is this PR dead now? It was going to provide really useful visibility

**Comment by enocom** [comment]
As mentioned in [#600](https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/600#issuecomment-771048045), we're working on some major structural improvements in addition to waiting for OpenTelemetry to go GA. Once those are done, we're going to circle back and add first-class support for metrics and tracing to the proxy. For now, I'd like to leave this PR open for reference in case others need Prometheus support with the caveat that we're not going to merge it.

**Comment by enocom** [comment]
As of https://github.com/GoogleCloudPlatform/cloudsql-proxy/pull/1215, we have support for Prometheus metrics in the v2 branch. We're working on a migration guide and making v2 the main branch, but until then I'm going to close this.

**Pull request closed without merging**
