### PR TITLE
fix(examples): Remove sidecar from no-proxy example.

### LINKED ISSUE #409: example deployment with Cloud SQL private IP not accurate
[The example](https://cloud.google.com/sql/docs/postgres/connect-kubernetes-engine#private-ip) is about **not** using the Cloud SQL proxy. Why does [the code line](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/54573d521428a322f8049b117854987830fa082a/examples/kubernetes/no_proxy_private_ip.yaml#L43) contain gcr.io/cloudsql-docker/gce-proxy as the 2nd container? Can I delete the 2nd container section and expect the GKE deployment to connect via private IP?

### PR DESCRIPTION
**Pull request by kurtisvg**
## Relevant issues:

- Fixes #409

### CODE REVIEW

**Comment by hilliao** [comment]
has a Google employee tested the new deployment yaml without [cloud-sql-proxy](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/54573d521428a322f8049b117854987830fa082a/examples/kubernetes/no_proxy_private_ip.yaml#L40)?

**Comment by kurtisvg** [comment]
@hilliao Is there a specific issue you are trying to diagnose? This examples is a _very_ generic deployment that doesn't contain anything specific to Cloud SQL. The goal is to highlight this be showing you can connect directly via IP

**Comment by hilliao** [comment]
1. I am submitting [doc feedback](https://cloud.google.com/sql/docs/postgres/connect-kubernetes-engine#private-ip) at  about the updated code. The doc still has old code.
2. Why does [the line](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/5f761d7ef539bfe4fb65c6856d439496cddbfcc7/examples/kubernetes/no_proxy_private_ip.yaml#L33) still says **START cloud_sql_proxy_secret_host**?

**Comment by kurtisvg** [comment]
@hilliao:

> 1. I am submitting [doc feedback](https://cloud.google.com/sql/docs/postgres/connect-kubernetes-engine#private-ip) at  about the updated code. The doc still has old code.
The documentation on that page automatically updates periodically based on the example in this repository. In fact, it looks like it's already updated.

> 2. Why does [the line](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/5f761d7ef539bfe4fb65c6856d439496cddbfcc7/examples/kubernetes/no_proxy_private_ip.yaml#L33) still says **START cloud_sql_proxy_secret_host**?

This is a comment, so it has no effect on the YAML. These are called region tags, and are what we use to dynamically link a section of code on our documentation.

**Pull request merged**
