### PR TITLE
Print out any errors during SIGTERM-caused shutdown

### PR DESCRIPTION
**Pull request by Carrotman42**
Before this change any error encountered during a forced shutdown via proxyClient.Shutdown will not be printed out, yet when there is an error the Proxy will still exit with a nonzero status. In addition to exiting with a nonzero status, this CL causes the errors to actually be printed out.

Note that log.Fatal(f) exits the program with exit code 1, which is a change from the prior implementation which exited with code 2. Let me know if exit code 2 was particularly important; I will happily log a message and explicitly exit(2).

I noticed this upon reading issue https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/388.

### CODE REVIEW

**Comment by kurtisvg** [comment]
Thanks for taking the time to PR these fixes. 

In the original PR, it doesn't look like 2 was picked for any specific reason. However, since it _was_ picked intentionally and mentioned in the PR, I'm hesitant to change it unless we have a good reason.

**Comment by Carrotman42** [comment]
+1, that is a very good point.

**Comment by karlkfi** [comment]
IME, 2 usually means user error, while 1 is general catchall.
This comes from a loose interpretation of [shell exit codes with special meaning](https://www.tldp.org/LDP/abs/html/exitcodes.html).

It probably originates from the [Bash manual](https://linux.die.net/man/1/bash), if not earlier.

> The return value is 0 if the string matches the pattern, and 1 otherwise. If the regular expression is syntactically incorrect, the conditional expression's return value is 2.

> Shell builtin commands return a status of 0 (true) if successful, and non-zero (false) if an error occurs while they execute. All builtins return an exit status of 2 to indicate incorrect usage.

An open connection could loosely be considered user error, tho I probably would have specified a different exit code for the case where the cause is the client operator's and not the server operator's fault.

**Comment by Carrotman42** [comment]
I agree that sometimes exit codes are documented to mean things. But IMHO if a specific exit code is not explicitly documented, it should not be relied on by users. Without more docs, exit codes should just be treated as Boolean, i.e. zero for success and nonzero for error.

Now that doesn't mean people won't rely on them without documentation :) which I why I agreed it'd be better to not change things given that it was easy to not change.

**Pull request merged**
