### PR TITLE
Publicly expose the driver so it can be wrapped

### PR DESCRIPTION
**Pull request by luna-duclos**
This lets tools such as https://github.com/luna-duclos/instrumentedsql wrap the driver and provide instrumentation.

### CODE REVIEW

**Comment by Carrotman42** [comment]
IMO it would be better if `github.com/lib/pq` were updated to allow custom dialers. Then this package wouldn't have to register a new driver just to allow a custom dialer, and this specialized logic could be made to look more like mysql/hook.go.

(although since we've already released a version where we register a database driver called `cloudsqlpostgres` we may be stuck supporting this thing forever anyway...)

**Comment by luna-duclos** [comment]
Any update on this ?

**Comment by broady** [comment]
Hey Luna,

I messaged you on the Gopher slack about this PR. Maybe we can chat there in realtime (probably tomorrow, since I think it's late where you are...)

> it would be better if github.com/lib/pq were updated to allow custom dialers.

It doesn't seem to have gotten much traction:
https://github.com/lib/pq/issues/470

Is there any reason not to expose this Driver except that it'd be better to do it a different way in lib/pq (if they'd even make that change)?

**Comment by Carrotman42** [comment]
> Is there any reason not to expose this Driver except that it'd be better to do it a different way in lib/pq (if they'd even make that change)?

That's my concern I suppose. I was trying to avoid the need to maintain it here. But if people want it and the other repo refuses to maintain it for us, I suppose we could exert the effort to make it better for our consumers.

**Comment by Carrotman42** [comment]
That, plus the database/SQL driver namespace is global, and I don't like adding to the global namespace of possible drivers if we don't have to. I'd rather piggyback off someone else's name to avoid collisions.

**Comment by broady** [comment]
@Carrotman42 any further objection?

Let's get this merged, if not. I think it's fair to say that adding support custom dialer registration to lib/pq is a long shot.

**Comment by Carrotman42** [comment]
Yeah just go ahead - I don't need to be a stick in the mud here for no great reason.

**Comment by hfwang** [comment]
Thanks for your patience Luna!

**Pull request merged**
