### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by strangemonad**
mismatched volume name

### CODE REVIEW

**Comment by strangemonad** [comment]
I signed it!

**Comment by strangemonad** [comment]
Clarification, I've submitted a corporate CLA for Inscriptive, Inc (opensource-contributors@inscriptive.com, shawn@inscriptive.com)

**Comment by Carrotman42** [comment]
@dlorenc wdyt? It seems like this CL is good, but I don't claim to understand the subject matter.

**Comment by dlorenc** [comment]
D'oh, yep, this looks correct. Not sure how I screwed that up copy-pasting.

I just got a full sample published in the container engine sample repo, I'll add a link to this readme when I get a chance. That has code users can clone to get started.

**Pull request merged**
